USE [Proyecto]
GO

/****** Object:  Table [dbo].[Fija]    Script Date: 11/23/2019 3:21:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Fija](
	[Id] [int] NOT NULL,
 CONSTRAINT [PK_Fija] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Fija]  WITH CHECK ADD  CONSTRAINT [FK_Fija_TipoDeduccion] FOREIGN KEY([Id])
REFERENCES [dbo].[TipoDeduccion] ([Id])
GO

ALTER TABLE [dbo].[Fija] CHECK CONSTRAINT [FK_Fija_TipoDeduccion]
GO

